import type { Metadata } from "next";
import * as React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });
export const runtime = "edge";

export const metadata: Metadata = {
  title: "wekul.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Analytics />
    <SpeedInsights />
      {/* TODO: Make this have top bar with good computer wizard type shiz of a logo */}
      {/* 
        Scheme contenders
          https://www.realtimecolors.com/?colors=e2ddf2-050309-a195d7-722b42-c47462&fonts=Poppins-Poppins
          https://www.realtimecolors.com/?colors=e1f5e4-091b0e-92dca1-2b7083-4480c2&fonts=Poppins-Poppins
          https://www.realtimecolors.com/?colors=e3eff9-06141f-95bee9-6f1b82-d73fad&fonts=Poppins-Poppins
          https://www.realtimecolors.com/?colors=d6e7fd-010e1e-6db1fa-8c06a2-f6159b&fonts=Poppins-Poppins
          https://www.realtimecolors.com/?colors=e2ebef-0a0e12-9fb7cb-413a6b-805ea7&fonts=Poppins-Poppins
          https://www.realtimecolors.com/?colors=002811-f4fff9-16fe74-6db0ff-3d63ff&fonts=Poppins-Poppins
        */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
